# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.java.home=C:\\Users\\elmat\\AppData\\Local\\Programs\\Eclipse Adoptium\\jdk-25.0.2.10-hotspot

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version = 1.8
maven_group = com.data_stream
archives_base_name = TiltBreak

# Dependencies
fabric_version=0.158.0+26.2